name: Pets
main: Pets\Pets
version: 1.0.0
api: [1.13.1, 2.0.0]
author: "TheLucyClub & LostTeam"
description: "Pets for PocketMine!"
commands:
  pet:
    usage: "/pet <Sub-Command|Help> [input]"
    description: "Base Pet Command"
    permission: pet.cmd
permissions:
  pet.cmd:
    default: true
    description: "Parent Pets Permission"
    children:
      pet.cmd.make:
        default: true
        description: "pet spawn permission"
      pet.cmd.name:
        default: true
        description: "pet renaming permission"
      pet.cmd.storage:
        default: true
        description: "pet inventory permission"
      pet.cmd.help:
        default: true
        description: "general help permission"
  pet.seeId:
    default: true
    description: "Permission for player to see their pets ID"